FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm cache clean --force && \
    npm ci && \
    npm rebuild esbuild

COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
