-- Historical note:
-- Attendance tables were already introduced in
-- 20260212120000_add_attendance_management.sql.
--
-- This later file was generated as a remote-schema artifact and duplicated the
-- attendance DDL with a weaker RLS policy set. It is intentionally kept as a
-- no-op so migration history remains stable without replaying duplicate schema.
